loot:
  - material: ENDER_PEARL
    amount: 1-3
  - material: GOLDEN_APPLE
    amount: 3-5
  - material: GOLDEN_CARROT
    amount: 16-32
  - material: IRON_INGOT
    amount: 6-10
  - material: DIAMOND
    amount: 6-10
  - material: IRON_HELMET
    enchantments:
      - type: UNBREAKING
        level: 3
      - type: PROTECTION
        level: 1-6
  - material: DIAMOND_HELMET
    enchantments:
      - type: UNBREAKING
        level: 3
      - type: PROTECTION
        level: 1-6
  - material: IRON_CHESTPLATE
    enchantments:
      - type: UNBREAKING
        level: 3
      - type: PROTECTION
        level: 1-6
  - material: DIAMOND_CHESTPLATE
    enchantments:
      - type: UNBREAKING
        level: 3
      - type: PROTECTION
        level: 1-6
  - material: IRON_LEGGINGS
    enchantments:
      - type: UNBREAKING
        level: 3
      - type: PROTECTION
        level: 1-6
  - material: DIAMOND_LEGGINGS
    enchantments:
      - type: UNBREAKING
        level: 3
      - type: PROTECTION
        level: 1-6
  - material: IRON_BOOTS
    enchantments:
      - type: UNBREAKING
        level: 3
      - type: PROTECTION
        level: 1-6
  - material: DIAMOND_BOOTS
    enchantments:
      - type: UNBREAKING
        level: 3
      - type: PROTECTION
        level: 1-6
  - material: IRON_AXE
    enchantments:
      - type: SHARPNESS
        level: 1-6
  - material: DIAMOND_AXE
    enchantments:
      - type: SHARPNESS
        level: 1-6
  - material: IRON_SWORD
    enchantments:
      - type: SHARPNESS
        level: 1-6
  - material: DIAMOND_SWORD
    enchantments:
      - type: SHARPNESS
        level: 1-6
  - material: TRIDENT
    enchantments:
      - type: RIPTIDE
        level: 3
      - type: UNBREAKING
        level: 3
  - material: DIAMOND_PICKAXE
    enchantments:
      - type: EFFICIENCY
        level: 5-10
      - type: UNBREAKING
        level: 3
  - material: NETHERITE_SWORD
    enchantments:
      - type: SHARPNESS
        level: 1-6
      - type: UNBREAKING
        level: 3
  - material: NETHERITE_AXE
    enchantments:
      - type: SHARPNESS
        level: 1-6
      - type: UNBREAKING
        level: 3
  - material: NETHERITE_PICKAXE
    enchantments:
      - type: EFFICIENCY
        level: 5-10
      - type: UNBREAKING
        level: 3
  - material: ELYTRA
  - material: ENCHANTED_GOLDEN_APPLE
    amount: 1-2
  - material: TOTEM_OF_UNDYING
  - material: MACE
    enchantments:
      - type: DENSITY
        level: 0-4
      - type: FIRE_ASPECT
        level: 0-1
